### ISSUE TITLE
Traduction de meta-refresh / help

### ISSUE THREAD

**Issue by PhilippeVay** [ffoodd/axe-core#5]
["help": "Un rafraîchissement après délai ne doit pas être exister"](https://github.com/ffoodd/axe-core/blob/8e9b3b0187c862e7a8ebd51347309308d9deb5cf/locales/fr.json#L194)

L'[original](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/meta-refresh.json) est : 

```
"description": "Ensures <meta http-equiv=\"refresh\"> is not used",
"help": "Timed refresh must not exist"
```

Est-ce que simplement enlever "être" suffit ? Ou "Il ne doit pas y avoir de rafraîchissement après délai" ? 'fin le terme "rafraîchissement après délai" me semble tellement bizarre que je n'arrive pas à traduire le reste… (mais ça doit être que moi, je n'ai jamais utilisé autre chose que refresh/rafraîchissement seul ou meta refresh en anglais)

**Comment by dzc34** [comment]
- via Google Translate : "L'actualisation temporisée ne doit pas exister"
- via deepl.com : "Le rafraîchissement chronométré ne doit pas exister."
  - pour ""Timed refresh" propose : 
    - "Rafraîchissement temporisé"
    - "Rafraîchissement programmé"
    - "Rafraîchissement synchronisé"

Le pb est que la version anglais est un peu minimaliste, car il n'est pas précisé que cela concerne la page entière. Proposition: "La page HTML ne doit pas être rechargé / actualisé automatiquement"

**Comment by ffoodd** [comment]
En effet le verbe « être » est de toute façon de trop ici.

La notion de _timed_ m’a parue importante, mais comme c’est une technique que je n’ai jamais employée je n’en connais pas vraiment les nuances : est-ce que « automatiquement » suffit à l’apporter, comme dans la proposition de @dzc34 ?

Sinon « rafraîchissement programmé » est peut-être plus pertinent que « après délai » ?
Qu’en dites-vous ?

**Comment by ffoodd** [comment]
La traduction que je viens de pousser est « La page HTML ne doit pas être actualisée automatiquement », qui me paraît la plus claire. Merci à vous deux !
